### ISSUE TITLE
How to get date and time on the status bar

### ISSUE THREAD

**Issue by oo92** [regolith-linux/regolith-i3-config#18]
Hi.

I've been looking all over the place for this. I can't get the date and time on my status bar. I am using Regolith on Ubuntu 22.10.

**Comment by kgilmer** [comment]
The package you're looking for is `i3xrocks-time`.  Agreed that it's not very easy to find a listing of these packages, but [here is some info](https://regolith-desktop.com/docs/howtos/add-remove-blocklets/) that may help before the docs are improved.
