### ISSUE TITLE
cant change font, and size of font in config file for i3 bar

### ISSUE THREAD

**Issue by pjbryan** [regolith-linux/regolith-i3-config#2]
using the pong:font. i still cant change the size and font of my i3 bar. searched up the issue and never found it solved

**Comment by kgilmer** [comment]
I was able to change the i3 bar font to DejaVu Sans 24 with this Xresource override (in the default look):

```
echo "gtk.monospace_font_name: DejaVu Sans 24" >> ~/.config/regolith2/Xresources
echo "i3xrocks.value.font: DejaVu Sans 24" >> ~/.config/regolith2/Xresources
regolith-look refresh
```

![image](https://user-images.githubusercontent.com/49683/172013602-b77a35bd-d05e-47bb-a23b-20d50a668d54.png)
