### ISSUE TITLE
cannot find the config that has all the keybinding.

### ISSUE THREAD

**Issue by pjbryan** [regolith-linux/regolith-i3-config#5]
After looking for centuries, the main reason I dont like Regolith 2.0 is i cannot find the configuration for the keybinds. i look into /etc/regolith/i3/config for the file, and its there, but when I open the file it is missing most of the keybinds. But when I add these keybindings, alot similiar to what I used in Regolith 1.6, it says there is an error, and some are duplicate.

Where are the keybindings kept? Because the config file is half empty. And all the xresources files are only the ones that I have made myself. I looked all over you documentation but the answer was no where to be found.

**Comment by kgilmer** [comment]
Hi @peejxyy ,

  Yes, you're right.  The documentation is missing key details in this regard.  I'm sorry to hear about your frustration and lost time.  There are [some comments in the i3 file that explains where the partials are stored](https://github.com/regolith-linux/regolith-i3-config/blob/master/config#L152-L156), but it would be easy to miss.  Based on your feedback, I've updated the [i3 configuration section on the website to include the details you're after](https://regolith-desktop.com/docs/using-regolith/configuration/#i3-features) and add some more details to make the setup more clear.

Please let me know if you have other feedback to improve Regolith documentation or other parts of the project! :sun_with_face:

**Comment by newptcai** [comment]
Where is the keybindings for opening control center? I couldn't find it anywhere.

**Comment by newptcai** [comment]
Also, no key for wifi, display, etc.

**Comment by ferdinandyb** [comment]
You are looking for `regolith-i3-gnome` see the documentation Ken linked.

**Comment by newptcai** [comment]
Found it. Thanks. I feel this probably should be installed when regolith is installed though.

**Comment by ferdinandyb** [comment]
I'm pretty sure it is installed, maybe something went south when you upgraded.

**Comment by ferdinandyb** [comment]
@peejxyy are you happy with Ken's updates to the documentation? Can this issue be closed?

**Comment by newptcai** [comment]
Yes. I think the issue can be closed.
