### ISSUE TITLE
i3-wm.bar.font in Xresources not respected

### ISSUE THREAD

**Issue by gmnz** [regolith-linux/regolith-i3-config#8]
Hi,

In my ".config/regolith2/Xresources" i have these two lines at the end of the file:

gnome.terminal.font: mononoki Nerd Font 10
i3-wm.bar.font: mononoki Nerd Font 10  

The gnome terminal font changes without any problem according to the line above, but no matter what I've tried the bar font setting is being ignored and I can't find out why. I'm using Regolith Desktop 2.1.

BTW, great distro/desktop! Thank you for your work! :-)

**Comment by kgilmer** [comment]
Hi @gmnz , hmm well the bar font is controlled by `gtk.monospace_font_name`, as specified here: https://github.com/regolith-linux/regolith-i3-config/blob/master/partials/70_bar#L11.  Admittedly it's a bit tricky to figure out how this is set.  not to mention incorrect documentation :grimacing: .  I'll get the docs fixed up, sorry for the confusion.

**Comment by gmnz** [comment]
_> hmm well the bar font is controlled by gtk.monospace_font_name_
I actually knew this, but thought the gnome terminal font was controlled by the same resource because I found something like that in the configs... That's why I didn't try changing its value. But it work, thanks. :-) It changes only the font size of the bar although if you make the font size e.g 30, the icons are much bigger than the text itself, but that's no problem for me, as I wanted to make the font <= 12 and then there's no such problem. :-) And don't apologize, I've been waiting for a desktop like this for years. :-) Though I haven't been using 1.6 much, cause it was missing a good light theme. :-D But that's fixed now in 2.1. :-)
